//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.261
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestadh45.services.Documents.Templates {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResDocuments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResDocuments() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestadh45.services.Documents.Templates.ResDocuments", typeof(ResDocuments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1} - {2}.
        /// </summary>
        internal static string LibelleAdresse {
            get {
                return ResourceManager.GetString("LibelleAdresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autorisation parentale pour les mineurs.
        /// </summary>
        internal static string LibelleAutorisationParentale {
            get {
                return ResourceManager.GetString("LibelleAutorisationParentale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cotisation : {0} euros.
        /// </summary>
        internal static string LibelleCotisation {
            get {
                return ResourceManager.GetString("LibelleCotisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fait à {0} le {1}.
        /// </summary>
        internal static string LibelleFaitALe {
            get {
                return ResourceManager.GetString("LibelleFaitALe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fait à .............................. le ...............................
        /// </summary>
        internal static string LibelleFaitALeVide {
            get {
                return ResourceManager.GetString("LibelleFaitALeVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe : {0}.
        /// </summary>
        internal static string LibelleGroupe {
            get {
                return ResourceManager.GetString("LibelleGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mail : {0}.
        /// </summary>
        internal static string LibelleMailClub {
            get {
                return ResourceManager.GetString("LibelleMailClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Né(e) le {0}.
        /// </summary>
        internal static string LibelleNeLe {
            get {
                return ResourceManager.GetString("LibelleNeLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1}.
        /// </summary>
        internal static string LibelleNomAdherent {
            get {
                return ResourceManager.GetString("LibelleNomAdherent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} - Saison {1}.
        /// </summary>
        internal static string LibelleNomClubSaison {
            get {
                return ResourceManager.GetString("LibelleNomClubSaison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° {0}.
        /// </summary>
        internal static string LibelleNumeroClub {
            get {
                return ResourceManager.GetString("LibelleNumeroClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reçu pour l&apos;adhésion {0} à {1}.
        /// </summary>
        internal static string LibelleRecuPourAdhesion {
            get {
                return ResourceManager.GetString("LibelleRecuPourAdhesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signature de l&apos;adhérent ou de son représentant légal.
        /// </summary>
        internal static string LibelleSignatureAdherent {
            get {
                return ResourceManager.GetString("LibelleSignatureAdherent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signature.
        /// </summary>
        internal static string LibelleSignatureParents {
            get {
                return ResourceManager.GetString("LibelleSignatureParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SIRET : {0}.
        /// </summary>
        internal static string LibelleSiret {
            get {
                return ResourceManager.GetString("LibelleSiret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web : {0}.
        /// </summary>
        internal static string LibelleSiteWebClub {
            get {
                return ResourceManager.GetString("LibelleSiteWebClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tel. : {0}.
        /// </summary>
        internal static string LibelleTelephone {
            get {
                return ResourceManager.GetString("LibelleTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} - {1}.
        /// </summary>
        internal static string LibelleTelMail {
            get {
                return ResourceManager.GetString("LibelleTelMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription {0} à {1}.
        /// </summary>
        internal static string LibelleTitreFicheInscription {
            get {
                return ResourceManager.GetString("LibelleTitreFicheInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je, soussigné .................................................., agissant en qualité de parent ou de tuteur légal de l&apos;enfant désigné ci-dessus, autorise le club à faire transporter mon enfant au centre hospitalier le plus proche si son état le nécessite ou a prendre toutes les mesures nécessaires en cas d&apos;accident survenant lors de la pratique de l&apos;escalade dans le cadre du club..
        /// </summary>
        internal static string TexteAutorisationParentale {
            get {
                return ResourceManager.GetString("TexteAutorisationParentale", resourceCulture);
            }
        }
    }
}
