//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.225
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestadh45.service.Graphs {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResGraphs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResGraphs() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestadh45.service.Graphs.ResGraphs", typeof(ResGraphs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extérieurs.
        /// </summary>
        public static string Libelle_Exterieurs {
            get {
                return ResourceManager.GetString("Libelle_Exterieurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Majeurs.
        /// </summary>
        public static string Libelle_Majeurs {
            get {
                return ResourceManager.GetString("Libelle_Majeurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mineurs.
        /// </summary>
        public static string Libelle_Mineurs {
            get {
                return ResourceManager.GetString("Libelle_Mineurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb. Adhérents.
        /// </summary>
        public static string Libelle_NbAdherents {
            get {
                return ResourceManager.GetString("Libelle_NbAdherents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résidents.
        /// </summary>
        public static string Libelle_Residents {
            get {
                return ResourceManager.GetString("Libelle_Residents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remplissage des groupes.
        /// </summary>
        public static string Titre_RemplissageGroupes {
            get {
                return ResourceManager.GetString("Titre_RemplissageGroupes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répartition des adhérents par âge.
        /// </summary>
        public static string Titre_RepartitionAges {
            get {
                return ResourceManager.GetString("Titre_RepartitionAges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répartition des adhérents majeurs / mineurs.
        /// </summary>
        public static string Titre_RepartitionMajeursMineurs {
            get {
                return ResourceManager.GetString("Titre_RepartitionMajeursMineurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répartition des adhérents résidents / extérieurs.
        /// </summary>
        public static string Titre_RepartitionResidentsExterieurs {
            get {
                return ResourceManager.GetString("Titre_RepartitionResidentsExterieurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répartition des adhérents par sexe.
        /// </summary>
        public static string Titre_RepartitionSexes {
            get {
                return ResourceManager.GetString("Titre_RepartitionSexes", resourceCulture);
            }
        }
    }
}
