//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace gestadh45.dal
{
    public partial class Saison
    {
        public Saison()
        {
            this.Groupes = new HashSet<Groupe>();
        }
    
        public long ID { get; set; }
        public bool EstSaisonCourante { get; set; }
        public long AnneeDebut { get; set; }
        public long AnneeFin { get; set; }
    
        public virtual ICollection<Groupe> Groupes { get; set; }
    }
    
}
