//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.237
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestadh45.Ihm.SpecialMessages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResMessages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestadh45.Ihm.SpecialMessages.ResMessages", typeof(ResMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;application a rencontré l&apos;erreur fatale suivante : .
        /// </summary>
        public static string ErreurFataleDebut {
            get {
                return ResourceManager.GetString("ErreurFataleDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour éviter tout problème d&apos;instabilité, l&apos;application va maintenant se fermer..
        /// </summary>
        public static string ErreurFataleInfoQuitter {
            get {
                return ResourceManager.GetString("ErreurFataleInfoQuitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adhérent a correctement été dupliqué.
        /// </summary>
        public static string MessageConfirmDuplicationAdherent {
            get {
                return ResourceManager.GetString("MessageConfirmDuplicationAdherent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer cet adhérent?.
        /// </summary>
        public static string MessageConfirmSupprAdherent {
            get {
                return ResourceManager.GetString("MessageConfirmSupprAdherent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer ce groupe?.
        /// </summary>
        public static string MessageConfirmSupprGroupe {
            get {
                return ResourceManager.GetString("MessageConfirmSupprGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer cette inscription?.
        /// </summary>
        public static string MessageConfirmSupprInscription {
            get {
                return ResourceManager.GetString("MessageConfirmSupprInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer cette saison?.
        /// </summary>
        public static string MessageConfirmSupprSaison {
            get {
                return ResourceManager.GetString("MessageConfirmSupprSaison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer cette tranche d&apos;âge?.
        /// </summary>
        public static string MessageConfirmSupprTrancheAge {
            get {
                return ResourceManager.GetString("MessageConfirmSupprTrancheAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer cette ville?.
        /// </summary>
        public static string MessageConfirmSupprVille {
            get {
                return ResourceManager.GetString("MessageConfirmSupprVille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste de mail correctement exportée dans : .
        /// </summary>
        public static string MessageInfoExtractionMails {
            get {
                return ResourceManager.GetString("MessageInfoExtractionMails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le document a correctement été généré.
        /// </summary>
        public static string MessageInfoGenerationDocument {
            get {
                return ResourceManager.GetString("MessageInfoGenerationDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les documents ont correctement été générés.
        /// </summary>
        public static string MessageInfoGenerationDocumentsGroupe {
            get {
                return ResourceManager.GetString("MessageInfoGenerationDocumentsGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La VCard a correctement été générée.
        /// </summary>
        public static string MessageInfoGenerationVCard {
            get {
                return ResourceManager.GetString("MessageInfoGenerationVCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les VCards ont correctement été générées.
        /// </summary>
        public static string MessageInfoGenerationVCardsGroupe {
            get {
                return ResourceManager.GetString("MessageInfoGenerationVCardsGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adhérent a correctement été supprimé.
        /// </summary>
        public static string MessageInfoSuppressionAdherent {
            get {
                return ResourceManager.GetString("MessageInfoSuppressionAdherent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le groupe a correctement été supprimé.
        /// </summary>
        public static string MessageInfoSuppressionGroupe {
            get {
                return ResourceManager.GetString("MessageInfoSuppressionGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;inscription a correctement été supprimé.
        /// </summary>
        public static string MessageInfoSuppressionInscription {
            get {
                return ResourceManager.GetString("MessageInfoSuppressionInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La saison a correctement été supprimée.
        /// </summary>
        public static string MessageInfoSuppressionSaison {
            get {
                return ResourceManager.GetString("MessageInfoSuppressionSaison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La tranche d&apos;âge a correctement été supprimée.
        /// </summary>
        public static string MessageInfoSuppressionTrancheAge {
            get {
                return ResourceManager.GetString("MessageInfoSuppressionTrancheAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La ville a correctement été supprimée.
        /// </summary>
        public static string MessageInfoSuppressionVille {
            get {
                return ResourceManager.GetString("MessageInfoSuppressionVille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        public static string TitreConfirmation {
            get {
                return ResourceManager.GetString("TitreConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        public static string TitreErreur {
            get {
                return ResourceManager.GetString("TitreErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exception.
        /// </summary>
        public static string TitreException {
            get {
                return ResourceManager.GetString("TitreException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        public static string TitreInformation {
            get {
                return ResourceManager.GetString("TitreInformation", resourceCulture);
            }
        }
    }
}
