//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.237
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestadh45.Ihm.ViewModel {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResErreurs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResErreurs() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestadh45.Ihm.ViewModel.ResErreurs", typeof(ResErreurs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adresse est obligatoire.
        /// </summary>
        internal static string Adherent_AdresseObligatoire {
            get {
                return ResourceManager.GetString("Adherent_AdresseObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date de naissance est obligatoire.
        /// </summary>
        internal static string Adherent_DateNaissanceObligatoire {
            get {
                return ResourceManager.GetString("Adherent_DateNaissanceObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet adhérent existe déjà (nom + prénom + date naissance).
        /// </summary>
        internal static string Adherent_Existe {
            get {
                return ResourceManager.GetString("Adherent_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom est obligatoire.
        /// </summary>
        internal static string Adherent_NomObligatoire {
            get {
                return ResourceManager.GetString("Adherent_NomObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le prénom est obligatoire.
        /// </summary>
        internal static string Adherent_PrenomObligatoire {
            get {
                return ResourceManager.GetString("Adherent_PrenomObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le sexe est obligatoire.
        /// </summary>
        internal static string Adherent_SexeObligatoire {
            get {
                return ResourceManager.GetString("Adherent_SexeObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La ville est obligatoire.
        /// </summary>
        internal static string Adherent_VilleObligatoire {
            get {
                return ResourceManager.GetString("Adherent_VilleObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Champ obligatoire.
        /// </summary>
        internal static string ChampObligatoire {
            get {
                return ResourceManager.GetString("ChampObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce groupe existe déjà (nom + jour + heure début).
        /// </summary>
        internal static string Groupe_Existe {
            get {
                return ResourceManager.GetString("Groupe_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;heure de début est obligatoire.
        /// </summary>
        internal static string Groupe_HeureDebutObligatoire {
            get {
                return ResourceManager.GetString("Groupe_HeureDebutObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;heure de fin est obligatoire.
        /// </summary>
        internal static string Groupe_HeureFinObligatoire {
            get {
                return ResourceManager.GetString("Groupe_HeureFinObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;heure de fin doit être strictement supérieure à l&apos;heure de début.
        /// </summary>
        internal static string Groupe_HeureFinSupHeureDebut {
            get {
                return ResourceManager.GetString("Groupe_HeureFinSupHeureDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le jour est obligatoire.
        /// </summary>
        internal static string Groupe_JourObligatoire {
            get {
                return ResourceManager.GetString("Groupe_JourObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le libellé est obligatoire.
        /// </summary>
        internal static string Groupe_LibelleObligatoire {
            get {
                return ResourceManager.GetString("Groupe_LibelleObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adresse est obligatoire.
        /// </summary>
        internal static string InfosClub_AdresseObligatoire {
            get {
                return ResourceManager.GetString("InfosClub_AdresseObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom est obligatoire.
        /// </summary>
        internal static string InfosClub_NomObligatoire {
            get {
                return ResourceManager.GetString("InfosClub_NomObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La ville est obligatoire.
        /// </summary>
        internal static string InfosClub_VilleObligatoire {
            get {
                return ResourceManager.GetString("InfosClub_VilleObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adhérent est obligatoire.
        /// </summary>
        internal static string Inscription_AdherentObligatoire {
            get {
                return ResourceManager.GetString("Inscription_AdherentObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette inscription existe déjà (adhérent+groupe).
        /// </summary>
        internal static string Inscription_Existe {
            get {
                return ResourceManager.GetString("Inscription_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le groupe est obligatoire.
        /// </summary>
        internal static string Inscription_GroupeObligatoire {
            get {
                return ResourceManager.GetString("Inscription_GroupeObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le statut est obligatoire.
        /// </summary>
        internal static string Inscription_StatutObligatoire {
            get {
                return ResourceManager.GetString("Inscription_StatutObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;année de début est obligatoire.
        /// </summary>
        internal static string Saison_AnneeDebutObligatoire {
            get {
                return ResourceManager.GetString("Saison_AnneeDebutObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;année de fin est obligatoire.
        /// </summary>
        internal static string Saison_AnneeFinObligatoire {
            get {
                return ResourceManager.GetString("Saison_AnneeFinObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;année de fin doit être strictement supérieure à l&apos;année de début.
        /// </summary>
        internal static string Saison_AnneeFinSupAnneeDebut {
            get {
                return ResourceManager.GetString("Saison_AnneeFinSupAnneeDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette saison existe déjà.
        /// </summary>
        internal static string Saison_Existe {
            get {
                return ResourceManager.GetString("Saison_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le code postal est obligatoire.
        /// </summary>
        internal static string Ville_CodePostalObligatoire {
            get {
                return ResourceManager.GetString("Ville_CodePostalObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette ville existe déjà.
        /// </summary>
        internal static string Ville_Existe {
            get {
                return ResourceManager.GetString("Ville_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le libellé est obligatoire.
        /// </summary>
        internal static string Ville_LibelleObligatoire {
            get {
                return ResourceManager.GetString("Ville_LibelleObligatoire", resourceCulture);
            }
        }
    }
}
