//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.225
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestadh45.service.Database {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResDatabase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResDatabase() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestadh45.service.Database.ResDatabase", typeof(ResDatabase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CREATE TABLE [Adherent] (
        ///
        ///    [ID] integer PRIMARY KEY AUTOINCREMENT NOT NULL,
        ///
        ///    [Nom] nvarchar(50) NOT NULL,
        ///
        ///    [Prenom] nvarchar(50) NOT NULL,
        ///
        ///    [DateNaissance] datetime NOT NULL,
        ///
        ///    [DateCreation] datetime NOT NULL,
        ///
        ///    [DateModification] datetime NOT NULL,
        ///
        ///    [ID_Sexe] integer NOT NULL,
        ///
        ///    [Commentaire] ntext NOT NULL,
        ///
        ///    [ID_Adresse] integer NOT NULL,
        ///
        ///    [ID_Contact] integer NOT NULL,
        ///
        ///    CONSTRAINT [FK_Adherent_0] FOREIGN KEY ([ID_Sexe]) REFERENCES [Sexe] ([I [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string SQL_CreateTables {
            get {
                return ResourceManager.GetString("SQL_CreateTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DROP TABLE IF EXISTS [Adherent];
        ///DROP TABLE IF EXISTS [Adresse];
        ///DROP TABLE IF EXISTS [Contact];
        ///DROP TABLE IF EXISTS [Groupe];
        ///DROP TABLE IF EXISTS [InfosClub];
        ///DROP TABLE IF EXISTS [Inscription];
        ///DROP TABLE IF EXISTS [JourSemaine];
        ///DROP TABLE IF EXISTS [Saison];
        ///DROP TABLE IF EXISTS [Sexe];
        ///DROP TABLE IF EXISTS [TarifConseille];
        ///DROP TABLE IF EXISTS [Ville];.
        /// </summary>
        public static string SQL_DropTables {
            get {
                return ResourceManager.GetString("SQL_DropTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -- Alimentation des tables de reference
        ///INSERT INTO JourSemaine VALUES(1,1,&apos;Lundi&apos;);
        ///INSERT INTO JourSemaine VALUES(2,2,&apos;Mardi&apos;);
        ///INSERT INTO JourSemaine VALUES(3,3,&apos;Mercredi&apos;);
        ///INSERT INTO JourSemaine VALUES(4,4,&apos;Jeudi&apos;);
        ///INSERT INTO JourSemaine VALUES(5,5,&apos;Vendredi&apos;);
        ///INSERT INTO JourSemaine VALUES(6,6,&apos;Samedi&apos;);
        ///INSERT INTO JourSemaine VALUES(7,7,&apos;Dimanche&apos;);
        ///
        ///INSERT INTO Sexe VALUES(1,&apos;M&apos;,&apos;Masculin&apos;);
        ///INSERT INTO Sexe VALUES(2,&apos;F&apos;,&apos;Féminin&apos;);
        ///
        ///-- Insertion des donnees indispensable pour lanc [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string SQL_InsertData {
            get {
                return ResourceManager.GetString("SQL_InsertData", resourceCulture);
            }
        }
    }
}
