//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace gestadh45.dal
{
    public partial class Equipement
    {
        public Equipement()
        {
            this.Verifications = new HashSet<Verification>();
        }
    
        public System.Guid ID { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> DateAchat { get; set; }
        public Nullable<System.DateTime> DateMiseEnService { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.DateTime DateModification { get; set; }
        public string Commentaire { get; set; }
        public System.Guid ID_Marque { get; set; }
        public System.Guid ID_Categorie { get; set; }
        public Nullable<System.DateTime> DateMiseAuRebut { get; set; }
        public System.Guid ID_DureeDeVie { get; set; }
    
        public virtual Marque Marque { get; set; }
        public virtual Categorie Categorie { get; set; }
        public virtual ICollection<Verification> Verifications { get; set; }
        public virtual DureeDeVie DureeDeVie { get; set; }
    }
    
}
