//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("Model", "FK_Adherent_0", "Sexe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(gestadh45.dal.Sexe), "Adherent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(gestadh45.dal.Adherent), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_Adherent_1", "Ville", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(gestadh45.dal.Ville), "Adherent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(gestadh45.dal.Adherent), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_Groupe_0", "JourSemaine", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(gestadh45.dal.JourSemaine), "Groupe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(gestadh45.dal.Groupe), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_Groupe_1", "Saison", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(gestadh45.dal.Saison), "Groupe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(gestadh45.dal.Groupe), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_InfosClub_0", "Ville", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(gestadh45.dal.Ville), "InfosClub", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(gestadh45.dal.InfosClub), true)]

#endregion

namespace gestadh45.dal
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet Entities à l'aide de la chaîne de connexion trouvée dans la section 'Entities' du fichier de configuration d'application.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet Entities.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet Entities.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Adherent> Adherents
        {
            get
            {
                if ((_Adherents == null))
                {
                    _Adherents = base.CreateObjectSet<Adherent>("Adherents");
                }
                return _Adherents;
            }
        }
        private ObjectSet<Adherent> _Adherents;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Groupe> Groupes
        {
            get
            {
                if ((_Groupes == null))
                {
                    _Groupes = base.CreateObjectSet<Groupe>("Groupes");
                }
                return _Groupes;
            }
        }
        private ObjectSet<Groupe> _Groupes;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<InfosClub> InfosClubs
        {
            get
            {
                if ((_InfosClubs == null))
                {
                    _InfosClubs = base.CreateObjectSet<InfosClub>("InfosClubs");
                }
                return _InfosClubs;
            }
        }
        private ObjectSet<InfosClub> _InfosClubs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Inscription> Inscriptions
        {
            get
            {
                if ((_Inscriptions == null))
                {
                    _Inscriptions = base.CreateObjectSet<Inscription>("Inscriptions");
                }
                return _Inscriptions;
            }
        }
        private ObjectSet<Inscription> _Inscriptions;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<JourSemaine> JourSemaines
        {
            get
            {
                if ((_JourSemaines == null))
                {
                    _JourSemaines = base.CreateObjectSet<JourSemaine>("JourSemaines");
                }
                return _JourSemaines;
            }
        }
        private ObjectSet<JourSemaine> _JourSemaines;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Saison> Saisons
        {
            get
            {
                if ((_Saisons == null))
                {
                    _Saisons = base.CreateObjectSet<Saison>("Saisons");
                }
                return _Saisons;
            }
        }
        private ObjectSet<Saison> _Saisons;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Sexe> Sexes
        {
            get
            {
                if ((_Sexes == null))
                {
                    _Sexes = base.CreateObjectSet<Sexe>("Sexes");
                }
                return _Sexes;
            }
        }
        private ObjectSet<Sexe> _Sexes;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<StatutInscription> StatutInscriptions
        {
            get
            {
                if ((_StatutInscriptions == null))
                {
                    _StatutInscriptions = base.CreateObjectSet<StatutInscription>("StatutInscriptions");
                }
                return _StatutInscriptions;
            }
        }
        private ObjectSet<StatutInscription> _StatutInscriptions;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Ville> Villes
        {
            get
            {
                if ((_Villes == null))
                {
                    _Villes = base.CreateObjectSet<Ville>("Villes");
                }
                return _Villes;
            }
        }
        private ObjectSet<Ville> _Villes;

        #endregion
        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Adherents. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToAdherents(Adherent adherent)
        {
            base.AddObject("Adherents", adherent);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Groupes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToGroupes(Groupe groupe)
        {
            base.AddObject("Groupes", groupe);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet InfosClubs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToInfosClubs(InfosClub infosClub)
        {
            base.AddObject("InfosClubs", infosClub);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Inscriptions. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToInscriptions(Inscription inscription)
        {
            base.AddObject("Inscriptions", inscription);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet JourSemaines. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToJourSemaines(JourSemaine jourSemaine)
        {
            base.AddObject("JourSemaines", jourSemaine);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Saisons. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToSaisons(Saison saison)
        {
            base.AddObject("Saisons", saison);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Sexes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToSexes(Sexe sexe)
        {
            base.AddObject("Sexes", sexe);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet StatutInscriptions. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToStatutInscriptions(StatutInscription statutInscription)
        {
            base.AddObject("StatutInscriptions", statutInscription);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Villes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToVilles(Ville ville)
        {
            base.AddObject("Villes", ville);
        }

        #endregion
    }
    

    #endregion
    
    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Adherent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Adherent : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Adherent.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        /// <param name="prenom">Valeur initiale de la propriété Prenom.</param>
        /// <param name="dateNaissance">Valeur initiale de la propriété DateNaissance.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="dateModification">Valeur initiale de la propriété DateModification.</param>
        /// <param name="iD_Sexe">Valeur initiale de la propriété ID_Sexe.</param>
        /// <param name="iD_Ville">Valeur initiale de la propriété ID_Ville.</param>
        public static Adherent CreateAdherent(global::System.Int64 id, global::System.String nom, global::System.String prenom, global::System.DateTime dateNaissance, global::System.DateTime dateCreation, global::System.DateTime dateModification, global::System.Int64 iD_Sexe, global::System.Int64 iD_Ville)
        {
            Adherent adherent = new Adherent();
            adherent.ID = id;
            adherent.Nom = nom;
            adherent.Prenom = prenom;
            adherent.DateNaissance = dateNaissance;
            adherent.DateCreation = dateCreation;
            adherent.DateModification = dateModification;
            adherent.ID_Sexe = iD_Sexe;
            adherent.ID_Ville = iD_Ville;
            return adherent;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Prenom
        {
            get
            {
                return _Prenom;
            }
            set
            {
                OnPrenomChanging(value);
                ReportPropertyChanging("Prenom");
                _Prenom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Prenom");
                OnPrenomChanged();
            }
        }
        private global::System.String _Prenom;
        partial void OnPrenomChanging(global::System.String value);
        partial void OnPrenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateNaissance
        {
            get
            {
                return _DateNaissance;
            }
            set
            {
                OnDateNaissanceChanging(value);
                ReportPropertyChanging("DateNaissance");
                _DateNaissance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateNaissance");
                OnDateNaissanceChanged();
            }
        }
        private global::System.DateTime _DateNaissance;
        partial void OnDateNaissanceChanging(global::System.DateTime value);
        partial void OnDateNaissanceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private global::System.DateTime _DateCreation;
        partial void OnDateCreationChanging(global::System.DateTime value);
        partial void OnDateCreationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateModification
        {
            get
            {
                return _DateModification;
            }
            set
            {
                OnDateModificationChanging(value);
                ReportPropertyChanging("DateModification");
                _DateModification = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateModification");
                OnDateModificationChanged();
            }
        }
        private global::System.DateTime _DateModification;
        partial void OnDateModificationChanging(global::System.DateTime value);
        partial void OnDateModificationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_Sexe
        {
            get
            {
                return _ID_Sexe;
            }
            set
            {
                OnID_SexeChanging(value);
                ReportPropertyChanging("ID_Sexe");
                _ID_Sexe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Sexe");
                OnID_SexeChanged();
            }
        }
        private global::System.Int64 _ID_Sexe;
        partial void OnID_SexeChanging(global::System.Int64 value);
        partial void OnID_SexeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Commentaire
        {
            get
            {
                return _Commentaire;
            }
            set
            {
                OnCommentaireChanging(value);
                ReportPropertyChanging("Commentaire");
                _Commentaire = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Commentaire");
                OnCommentaireChanged();
            }
        }
        private global::System.String _Commentaire;
        partial void OnCommentaireChanging(global::System.String value);
        partial void OnCommentaireChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adresse
        {
            get
            {
                return _Adresse;
            }
            set
            {
                OnAdresseChanging(value);
                ReportPropertyChanging("Adresse");
                _Adresse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adresse");
                OnAdresseChanged();
            }
        }
        private global::System.String _Adresse;
        partial void OnAdresseChanging(global::System.String value);
        partial void OnAdresseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_Ville
        {
            get
            {
                return _ID_Ville;
            }
            set
            {
                OnID_VilleChanging(value);
                ReportPropertyChanging("ID_Ville");
                _ID_Ville = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Ville");
                OnID_VilleChanged();
            }
        }
        private global::System.Int64 _ID_Ville;
        partial void OnID_VilleChanging(global::System.Int64 value);
        partial void OnID_VilleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telephone1
        {
            get
            {
                return _Telephone1;
            }
            set
            {
                OnTelephone1Changing(value);
                ReportPropertyChanging("Telephone1");
                _Telephone1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telephone1");
                OnTelephone1Changed();
            }
        }
        private global::System.String _Telephone1;
        partial void OnTelephone1Changing(global::System.String value);
        partial void OnTelephone1Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telephone2
        {
            get
            {
                return _Telephone2;
            }
            set
            {
                OnTelephone2Changing(value);
                ReportPropertyChanging("Telephone2");
                _Telephone2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telephone2");
                OnTelephone2Changed();
            }
        }
        private global::System.String _Telephone2;
        partial void OnTelephone2Changing(global::System.String value);
        partial void OnTelephone2Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telephone3
        {
            get
            {
                return _Telephone3;
            }
            set
            {
                OnTelephone3Changing(value);
                ReportPropertyChanging("Telephone3");
                _Telephone3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telephone3");
                OnTelephone3Changed();
            }
        }
        private global::System.String _Telephone3;
        partial void OnTelephone3Changing(global::System.String value);
        partial void OnTelephone3Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mail1
        {
            get
            {
                return _Mail1;
            }
            set
            {
                OnMail1Changing(value);
                ReportPropertyChanging("Mail1");
                _Mail1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mail1");
                OnMail1Changed();
            }
        }
        private global::System.String _Mail1;
        partial void OnMail1Changing(global::System.String value);
        partial void OnMail1Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mail2
        {
            get
            {
                return _Mail2;
            }
            set
            {
                OnMail2Changing(value);
                ReportPropertyChanging("Mail2");
                _Mail2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mail2");
                OnMail2Changed();
            }
        }
        private global::System.String _Mail2;
        partial void OnMail2Changing(global::System.String value);
        partial void OnMail2Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mail3
        {
            get
            {
                return _Mail3;
            }
            set
            {
                OnMail3Changing(value);
                ReportPropertyChanging("Mail3");
                _Mail3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mail3");
                OnMail3Changed();
            }
        }
        private global::System.String _Mail3;
        partial void OnMail3Changing(global::System.String value);
        partial void OnMail3Changed();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Adherent_0", "Sexe")]
        public Sexe Sexe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sexe>("Model.FK_Adherent_0", "Sexe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sexe>("Model.FK_Adherent_0", "Sexe").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sexe> SexeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sexe>("Model.FK_Adherent_0", "Sexe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sexe>("Model.FK_Adherent_0", "Sexe", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Adherent_1", "Ville")]
        public Ville Ville
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ville>("Model.FK_Adherent_1", "Ville").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ville>("Model.FK_Adherent_1", "Ville").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ville> VilleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ville>("Model.FK_Adherent_1", "Ville");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ville>("Model.FK_Adherent_1", "Ville", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Groupe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Groupe : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Groupe.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="libelle">Valeur initiale de la propriété Libelle.</param>
        /// <param name="iD_JourSemaine">Valeur initiale de la propriété ID_JourSemaine.</param>
        /// <param name="nbPlaces">Valeur initiale de la propriété NbPlaces.</param>
        /// <param name="iD_Saison">Valeur initiale de la propriété ID_Saison.</param>
        /// <param name="heureDebut">Valeur initiale de la propriété HeureDebut.</param>
        /// <param name="heureFin">Valeur initiale de la propriété HeureFin.</param>
        public static Groupe CreateGroupe(global::System.Int64 id, global::System.String libelle, global::System.Int64 iD_JourSemaine, global::System.Int64 nbPlaces, global::System.Int64 iD_Saison, global::System.DateTime heureDebut, global::System.DateTime heureFin)
        {
            Groupe groupe = new Groupe();
            groupe.ID = id;
            groupe.Libelle = libelle;
            groupe.ID_JourSemaine = iD_JourSemaine;
            groupe.NbPlaces = nbPlaces;
            groupe.ID_Saison = iD_Saison;
            groupe.HeureDebut = heureDebut;
            groupe.HeureFin = heureFin;
            return groupe;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Libelle
        {
            get
            {
                return _Libelle;
            }
            set
            {
                OnLibelleChanging(value);
                ReportPropertyChanging("Libelle");
                _Libelle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Libelle");
                OnLibelleChanged();
            }
        }
        private global::System.String _Libelle;
        partial void OnLibelleChanging(global::System.String value);
        partial void OnLibelleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_JourSemaine
        {
            get
            {
                return _ID_JourSemaine;
            }
            set
            {
                OnID_JourSemaineChanging(value);
                ReportPropertyChanging("ID_JourSemaine");
                _ID_JourSemaine = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_JourSemaine");
                OnID_JourSemaineChanged();
            }
        }
        private global::System.Int64 _ID_JourSemaine;
        partial void OnID_JourSemaineChanging(global::System.Int64 value);
        partial void OnID_JourSemaineChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 NbPlaces
        {
            get
            {
                return _NbPlaces;
            }
            set
            {
                OnNbPlacesChanging(value);
                ReportPropertyChanging("NbPlaces");
                _NbPlaces = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NbPlaces");
                OnNbPlacesChanged();
            }
        }
        private global::System.Int64 _NbPlaces;
        partial void OnNbPlacesChanging(global::System.Int64 value);
        partial void OnNbPlacesChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Commentaire
        {
            get
            {
                return _Commentaire;
            }
            set
            {
                OnCommentaireChanging(value);
                ReportPropertyChanging("Commentaire");
                _Commentaire = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Commentaire");
                OnCommentaireChanged();
            }
        }
        private global::System.String _Commentaire;
        partial void OnCommentaireChanging(global::System.String value);
        partial void OnCommentaireChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_Saison
        {
            get
            {
                return _ID_Saison;
            }
            set
            {
                OnID_SaisonChanging(value);
                ReportPropertyChanging("ID_Saison");
                _ID_Saison = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Saison");
                OnID_SaisonChanged();
            }
        }
        private global::System.Int64 _ID_Saison;
        partial void OnID_SaisonChanging(global::System.Int64 value);
        partial void OnID_SaisonChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime HeureDebut
        {
            get
            {
                return _HeureDebut;
            }
            set
            {
                OnHeureDebutChanging(value);
                ReportPropertyChanging("HeureDebut");
                _HeureDebut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeureDebut");
                OnHeureDebutChanged();
            }
        }
        private global::System.DateTime _HeureDebut;
        partial void OnHeureDebutChanging(global::System.DateTime value);
        partial void OnHeureDebutChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime HeureFin
        {
            get
            {
                return _HeureFin;
            }
            set
            {
                OnHeureFinChanging(value);
                ReportPropertyChanging("HeureFin");
                _HeureFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeureFin");
                OnHeureFinChanged();
            }
        }
        private global::System.DateTime _HeureFin;
        partial void OnHeureFinChanging(global::System.DateTime value);
        partial void OnHeureFinChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Groupe_0", "JourSemaine")]
        public JourSemaine JourSemaine
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JourSemaine>("Model.FK_Groupe_0", "JourSemaine").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JourSemaine>("Model.FK_Groupe_0", "JourSemaine").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<JourSemaine> JourSemaineReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JourSemaine>("Model.FK_Groupe_0", "JourSemaine");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<JourSemaine>("Model.FK_Groupe_0", "JourSemaine", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Groupe_1", "Saison")]
        public Saison Saison
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Saison>("Model.FK_Groupe_1", "Saison").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Saison>("Model.FK_Groupe_1", "Saison").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Saison> SaisonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Saison>("Model.FK_Groupe_1", "Saison");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Saison>("Model.FK_Groupe_1", "Saison", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="InfosClub")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InfosClub : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet InfosClub.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        public static InfosClub CreateInfosClub(global::System.Int64 id, global::System.String nom)
        {
            InfosClub infosClub = new InfosClub();
            infosClub.ID = id;
            infosClub.Nom = nom;
            return infosClub;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.String _Numero;
        partial void OnNumeroChanging(global::System.String value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Siren
        {
            get
            {
                return _Siren;
            }
            set
            {
                OnSirenChanging(value);
                ReportPropertyChanging("Siren");
                _Siren = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Siren");
                OnSirenChanged();
            }
        }
        private global::System.String _Siren;
        partial void OnSirenChanging(global::System.String value);
        partial void OnSirenChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NIC
        {
            get
            {
                return _NIC;
            }
            set
            {
                OnNICChanging(value);
                ReportPropertyChanging("NIC");
                _NIC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NIC");
                OnNICChanged();
            }
        }
        private global::System.String _NIC;
        partial void OnNICChanging(global::System.String value);
        partial void OnNICChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adresse
        {
            get
            {
                return _Adresse;
            }
            set
            {
                OnAdresseChanging(value);
                ReportPropertyChanging("Adresse");
                _Adresse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adresse");
                OnAdresseChanged();
            }
        }
        private global::System.String _Adresse;
        partial void OnAdresseChanging(global::System.String value);
        partial void OnAdresseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ID_Ville
        {
            get
            {
                return _ID_Ville;
            }
            set
            {
                OnID_VilleChanging(value);
                ReportPropertyChanging("ID_Ville");
                _ID_Ville = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Ville");
                OnID_VilleChanged();
            }
        }
        private Nullable<global::System.Int64> _ID_Ville;
        partial void OnID_VilleChanging(Nullable<global::System.Int64> value);
        partial void OnID_VilleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private global::System.String _Telephone;
        partial void OnTelephoneChanging(global::System.String value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mail
        {
            get
            {
                return _Mail;
            }
            set
            {
                OnMailChanging(value);
                ReportPropertyChanging("Mail");
                _Mail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mail");
                OnMailChanged();
            }
        }
        private global::System.String _Mail;
        partial void OnMailChanging(global::System.String value);
        partial void OnMailChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SiteWeb
        {
            get
            {
                return _SiteWeb;
            }
            set
            {
                OnSiteWebChanging(value);
                ReportPropertyChanging("SiteWeb");
                _SiteWeb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SiteWeb");
                OnSiteWebChanged();
            }
        }
        private global::System.String _SiteWeb;
        partial void OnSiteWebChanging(global::System.String value);
        partial void OnSiteWebChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_InfosClub_0", "Ville")]
        public Ville Ville
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ville>("Model.FK_InfosClub_0", "Ville").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ville>("Model.FK_InfosClub_0", "Ville").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ville> VilleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ville>("Model.FK_InfosClub_0", "Ville");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ville>("Model.FK_InfosClub_0", "Ville", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Inscription")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Inscription : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Inscription.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="iD_Adherent">Valeur initiale de la propriété ID_Adherent.</param>
        /// <param name="iD_Groupe">Valeur initiale de la propriété ID_Groupe.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="dateModification">Valeur initiale de la propriété DateModification.</param>
        /// <param name="iD_StatutInscription">Valeur initiale de la propriété ID_StatutInscription.</param>
        /// <param name="certificatMedicalRemis">Valeur initiale de la propriété CertificatMedicalRemis.</param>
        public static Inscription CreateInscription(global::System.Int64 id, global::System.Int64 iD_Adherent, global::System.Int64 iD_Groupe, global::System.DateTime dateCreation, global::System.DateTime dateModification, global::System.Int64 iD_StatutInscription, global::System.Boolean certificatMedicalRemis)
        {
            Inscription inscription = new Inscription();
            inscription.ID = id;
            inscription.ID_Adherent = iD_Adherent;
            inscription.ID_Groupe = iD_Groupe;
            inscription.DateCreation = dateCreation;
            inscription.DateModification = dateModification;
            inscription.ID_StatutInscription = iD_StatutInscription;
            inscription.CertificatMedicalRemis = certificatMedicalRemis;
            return inscription;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_Adherent
        {
            get
            {
                return _ID_Adherent;
            }
            set
            {
                OnID_AdherentChanging(value);
                ReportPropertyChanging("ID_Adherent");
                _ID_Adherent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Adherent");
                OnID_AdherentChanged();
            }
        }
        private global::System.Int64 _ID_Adherent;
        partial void OnID_AdherentChanging(global::System.Int64 value);
        partial void OnID_AdherentChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_Groupe
        {
            get
            {
                return _ID_Groupe;
            }
            set
            {
                OnID_GroupeChanging(value);
                ReportPropertyChanging("ID_Groupe");
                _ID_Groupe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Groupe");
                OnID_GroupeChanged();
            }
        }
        private global::System.Int64 _ID_Groupe;
        partial void OnID_GroupeChanging(global::System.Int64 value);
        partial void OnID_GroupeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Cotisation
        {
            get
            {
                return _Cotisation;
            }
            set
            {
                OnCotisationChanging(value);
                ReportPropertyChanging("Cotisation");
                _Cotisation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cotisation");
                OnCotisationChanged();
            }
        }
        private Nullable<global::System.Decimal> _Cotisation;
        partial void OnCotisationChanging(Nullable<global::System.Decimal> value);
        partial void OnCotisationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private global::System.DateTime _DateCreation;
        partial void OnDateCreationChanging(global::System.DateTime value);
        partial void OnDateCreationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateModification
        {
            get
            {
                return _DateModification;
            }
            set
            {
                OnDateModificationChanging(value);
                ReportPropertyChanging("DateModification");
                _DateModification = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateModification");
                OnDateModificationChanged();
            }
        }
        private global::System.DateTime _DateModification;
        partial void OnDateModificationChanging(global::System.DateTime value);
        partial void OnDateModificationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Commentaire
        {
            get
            {
                return _Commentaire;
            }
            set
            {
                OnCommentaireChanging(value);
                ReportPropertyChanging("Commentaire");
                _Commentaire = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Commentaire");
                OnCommentaireChanged();
            }
        }
        private global::System.String _Commentaire;
        partial void OnCommentaireChanging(global::System.String value);
        partial void OnCommentaireChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID_StatutInscription
        {
            get
            {
                return _ID_StatutInscription;
            }
            set
            {
                OnID_StatutInscriptionChanging(value);
                ReportPropertyChanging("ID_StatutInscription");
                _ID_StatutInscription = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_StatutInscription");
                OnID_StatutInscriptionChanged();
            }
        }
        private global::System.Int64 _ID_StatutInscription;
        partial void OnID_StatutInscriptionChanging(global::System.Int64 value);
        partial void OnID_StatutInscriptionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean CertificatMedicalRemis
        {
            get
            {
                return _CertificatMedicalRemis;
            }
            set
            {
                OnCertificatMedicalRemisChanging(value);
                ReportPropertyChanging("CertificatMedicalRemis");
                _CertificatMedicalRemis = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CertificatMedicalRemis");
                OnCertificatMedicalRemisChanged();
            }
        }
        private global::System.Boolean _CertificatMedicalRemis;
        partial void OnCertificatMedicalRemisChanging(global::System.Boolean value);
        partial void OnCertificatMedicalRemisChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="JourSemaine")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class JourSemaine : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet JourSemaine.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="numero">Valeur initiale de la propriété Numero.</param>
        /// <param name="libelle">Valeur initiale de la propriété Libelle.</param>
        public static JourSemaine CreateJourSemaine(global::System.Int64 id, global::System.Int64 numero, global::System.String libelle)
        {
            JourSemaine jourSemaine = new JourSemaine();
            jourSemaine.ID = id;
            jourSemaine.Numero = numero;
            jourSemaine.Libelle = libelle;
            return jourSemaine;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.Int64 _Numero;
        partial void OnNumeroChanging(global::System.Int64 value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Libelle
        {
            get
            {
                return _Libelle;
            }
            set
            {
                OnLibelleChanging(value);
                ReportPropertyChanging("Libelle");
                _Libelle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Libelle");
                OnLibelleChanged();
            }
        }
        private global::System.String _Libelle;
        partial void OnLibelleChanging(global::System.String value);
        partial void OnLibelleChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Groupe_0", "Groupe")]
        public EntityCollection<Groupe> Groupes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Groupe>("Model.FK_Groupe_0", "Groupe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Groupe>("Model.FK_Groupe_0", "Groupe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Saison")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Saison : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Saison.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="estSaisonCourante">Valeur initiale de la propriété EstSaisonCourante.</param>
        /// <param name="anneeDebut">Valeur initiale de la propriété AnneeDebut.</param>
        /// <param name="anneeFin">Valeur initiale de la propriété AnneeFin.</param>
        public static Saison CreateSaison(global::System.Int64 id, global::System.Boolean estSaisonCourante, global::System.Int64 anneeDebut, global::System.Int64 anneeFin)
        {
            Saison saison = new Saison();
            saison.ID = id;
            saison.EstSaisonCourante = estSaisonCourante;
            saison.AnneeDebut = anneeDebut;
            saison.AnneeFin = anneeFin;
            return saison;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EstSaisonCourante
        {
            get
            {
                return _EstSaisonCourante;
            }
            set
            {
                OnEstSaisonCouranteChanging(value);
                ReportPropertyChanging("EstSaisonCourante");
                _EstSaisonCourante = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EstSaisonCourante");
                OnEstSaisonCouranteChanged();
            }
        }
        private global::System.Boolean _EstSaisonCourante;
        partial void OnEstSaisonCouranteChanging(global::System.Boolean value);
        partial void OnEstSaisonCouranteChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AnneeDebut
        {
            get
            {
                return _AnneeDebut;
            }
            set
            {
                OnAnneeDebutChanging(value);
                ReportPropertyChanging("AnneeDebut");
                _AnneeDebut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnneeDebut");
                OnAnneeDebutChanged();
            }
        }
        private global::System.Int64 _AnneeDebut;
        partial void OnAnneeDebutChanging(global::System.Int64 value);
        partial void OnAnneeDebutChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AnneeFin
        {
            get
            {
                return _AnneeFin;
            }
            set
            {
                OnAnneeFinChanging(value);
                ReportPropertyChanging("AnneeFin");
                _AnneeFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnneeFin");
                OnAnneeFinChanged();
            }
        }
        private global::System.Int64 _AnneeFin;
        partial void OnAnneeFinChanging(global::System.Int64 value);
        partial void OnAnneeFinChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Groupe_1", "Groupe")]
        public EntityCollection<Groupe> Groupes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Groupe>("Model.FK_Groupe_1", "Groupe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Groupe>("Model.FK_Groupe_1", "Groupe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Sexe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sexe : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Sexe.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="libelleCourt">Valeur initiale de la propriété LibelleCourt.</param>
        /// <param name="libelleLong">Valeur initiale de la propriété LibelleLong.</param>
        public static Sexe CreateSexe(global::System.Int64 id, global::System.String libelleCourt, global::System.String libelleLong)
        {
            Sexe sexe = new Sexe();
            sexe.ID = id;
            sexe.LibelleCourt = libelleCourt;
            sexe.LibelleLong = libelleLong;
            return sexe;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LibelleCourt
        {
            get
            {
                return _LibelleCourt;
            }
            set
            {
                OnLibelleCourtChanging(value);
                ReportPropertyChanging("LibelleCourt");
                _LibelleCourt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LibelleCourt");
                OnLibelleCourtChanged();
            }
        }
        private global::System.String _LibelleCourt;
        partial void OnLibelleCourtChanging(global::System.String value);
        partial void OnLibelleCourtChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LibelleLong
        {
            get
            {
                return _LibelleLong;
            }
            set
            {
                OnLibelleLongChanging(value);
                ReportPropertyChanging("LibelleLong");
                _LibelleLong = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LibelleLong");
                OnLibelleLongChanged();
            }
        }
        private global::System.String _LibelleLong;
        partial void OnLibelleLongChanging(global::System.String value);
        partial void OnLibelleLongChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Adherent_0", "Adherent")]
        public EntityCollection<Adherent> Adherents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Adherent>("Model.FK_Adherent_0", "Adherent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Adherent>("Model.FK_Adherent_0", "Adherent", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="StatutInscription")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StatutInscription : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet StatutInscription.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="libelle">Valeur initiale de la propriété Libelle.</param>
        /// <param name="codeCouleur">Valeur initiale de la propriété CodeCouleur.</param>
        /// <param name="ordre">Valeur initiale de la propriété Ordre.</param>
        public static StatutInscription CreateStatutInscription(global::System.Int64 id, global::System.String libelle, global::System.String codeCouleur, global::System.Int64 ordre)
        {
            StatutInscription statutInscription = new StatutInscription();
            statutInscription.ID = id;
            statutInscription.Libelle = libelle;
            statutInscription.CodeCouleur = codeCouleur;
            statutInscription.Ordre = ordre;
            return statutInscription;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Libelle
        {
            get
            {
                return _Libelle;
            }
            set
            {
                OnLibelleChanging(value);
                ReportPropertyChanging("Libelle");
                _Libelle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Libelle");
                OnLibelleChanged();
            }
        }
        private global::System.String _Libelle;
        partial void OnLibelleChanging(global::System.String value);
        partial void OnLibelleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodeCouleur
        {
            get
            {
                return _CodeCouleur;
            }
            set
            {
                OnCodeCouleurChanging(value);
                ReportPropertyChanging("CodeCouleur");
                _CodeCouleur = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CodeCouleur");
                OnCodeCouleurChanged();
            }
        }
        private global::System.String _CodeCouleur;
        partial void OnCodeCouleurChanging(global::System.String value);
        partial void OnCodeCouleurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Ordre
        {
            get
            {
                return _Ordre;
            }
            set
            {
                OnOrdreChanging(value);
                ReportPropertyChanging("Ordre");
                _Ordre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ordre");
                OnOrdreChanged();
            }
        }
        private global::System.Int64 _Ordre;
        partial void OnOrdreChanging(global::System.Int64 value);
        partial void OnOrdreChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Ville")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ville : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Ville.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="libelle">Valeur initiale de la propriété Libelle.</param>
        /// <param name="codePostal">Valeur initiale de la propriété CodePostal.</param>
        public static Ville CreateVille(global::System.Int64 id, global::System.String libelle, global::System.String codePostal)
        {
            Ville ville = new Ville();
            ville.ID = id;
            ville.Libelle = libelle;
            ville.CodePostal = codePostal;
            return ville;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Libelle
        {
            get
            {
                return _Libelle;
            }
            set
            {
                OnLibelleChanging(value);
                ReportPropertyChanging("Libelle");
                _Libelle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Libelle");
                OnLibelleChanged();
            }
        }
        private global::System.String _Libelle;
        partial void OnLibelleChanging(global::System.String value);
        partial void OnLibelleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodePostal
        {
            get
            {
                return _CodePostal;
            }
            set
            {
                OnCodePostalChanging(value);
                ReportPropertyChanging("CodePostal");
                _CodePostal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CodePostal");
                OnCodePostalChanged();
            }
        }
        private global::System.String _CodePostal;
        partial void OnCodePostalChanging(global::System.String value);
        partial void OnCodePostalChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Adherent_1", "Adherent")]
        public EntityCollection<Adherent> Adherents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Adherent>("Model.FK_Adherent_1", "Adherent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Adherent>("Model.FK_Adherent_1", "Adherent", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_InfosClub_0", "InfosClub")]
        public EntityCollection<InfosClub> InfosClubs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InfosClub>("Model.FK_InfosClub_0", "InfosClub");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InfosClub>("Model.FK_InfosClub_0", "InfosClub", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
