//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace gestadh45.dal
{
    public partial class Verification
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_Equipement { get; set; }
        public System.Guid ID_StatutVerification { get; set; }
        public System.Guid ID_CampagneVerification { get; set; }
        public string Commentaire { get; set; }
    
        public virtual CampagneVerification CampagneVerification { get; set; }
        public virtual Equipement Equipement { get; set; }
        public virtual StatutVerification StatutVerification { get; set; }
    }
    
}
