//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace gestadh45.dal
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class gestadh45Entities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet gestadh45Entities à l'aide de la chaîne de connexion trouvée dans la section 'gestadh45Entities' du fichier de configuration d'application.
        /// </summary>
        public gestadh45Entities() : base("name=gestadh45Entities", "gestadh45Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet gestadh45Entities.
        /// </summary>
        public gestadh45Entities(string connectionString) : base(connectionString, "gestadh45Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet gestadh45Entities.
        /// </summary>
        public gestadh45Entities(EntityConnection connection) : base(connection, "gestadh45Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Groupe> Groupes
        {
            get
            {
                if ((_Groupes == null))
                {
                    _Groupes = base.CreateObjectSet<Groupe>("Groupes");
                }
                return _Groupes;
            }
        }
        private ObjectSet<Groupe> _Groupes;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<InfosClub> InfosClubs
        {
            get
            {
                if ((_InfosClubs == null))
                {
                    _InfosClubs = base.CreateObjectSet<InfosClub>("InfosClubs");
                }
                return _InfosClubs;
            }
        }
        private ObjectSet<InfosClub> _InfosClubs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<JourSemaine> JourSemaines
        {
            get
            {
                if ((_JourSemaines == null))
                {
                    _JourSemaines = base.CreateObjectSet<JourSemaine>("JourSemaines");
                }
                return _JourSemaines;
            }
        }
        private ObjectSet<JourSemaine> _JourSemaines;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Saison> Saisons
        {
            get
            {
                if ((_Saisons == null))
                {
                    _Saisons = base.CreateObjectSet<Saison>("Saisons");
                }
                return _Saisons;
            }
        }
        private ObjectSet<Saison> _Saisons;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Sexe> Sexes
        {
            get
            {
                if ((_Sexes == null))
                {
                    _Sexes = base.CreateObjectSet<Sexe>("Sexes");
                }
                return _Sexes;
            }
        }
        private ObjectSet<Sexe> _Sexes;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<StatutInscription> StatutInscriptions
        {
            get
            {
                if ((_StatutInscriptions == null))
                {
                    _StatutInscriptions = base.CreateObjectSet<StatutInscription>("StatutInscriptions");
                }
                return _StatutInscriptions;
            }
        }
        private ObjectSet<StatutInscription> _StatutInscriptions;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<TrancheAge> TrancheAges
        {
            get
            {
                if ((_TrancheAges == null))
                {
                    _TrancheAges = base.CreateObjectSet<TrancheAge>("TrancheAges");
                }
                return _TrancheAges;
            }
        }
        private ObjectSet<TrancheAge> _TrancheAges;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Ville> Villes
        {
            get
            {
                if ((_Villes == null))
                {
                    _Villes = base.CreateObjectSet<Ville>("Villes");
                }
                return _Villes;
            }
        }
        private ObjectSet<Ville> _Villes;

        #endregion
        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Groupes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToGroupes(Groupe groupe)
        {
            base.AddObject("Groupes", groupe);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet InfosClubs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToInfosClubs(InfosClub infosClub)
        {
            base.AddObject("InfosClubs", infosClub);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet JourSemaines. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToJourSemaines(JourSemaine jourSemaine)
        {
            base.AddObject("JourSemaines", jourSemaine);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Saisons. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToSaisons(Saison saison)
        {
            base.AddObject("Saisons", saison);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Sexes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToSexes(Sexe sexe)
        {
            base.AddObject("Sexes", sexe);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet StatutInscriptions. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToStatutInscriptions(StatutInscription statutInscription)
        {
            base.AddObject("StatutInscriptions", statutInscription);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet TrancheAges. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToTrancheAges(TrancheAge trancheAge)
        {
            base.AddObject("TrancheAges", trancheAge);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Villes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToVilles(Ville ville)
        {
            base.AddObject("Villes", ville);
        }

        #endregion
    }
    

    #endregion
    
    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gestadh45Model", Name="Groupe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Groupe : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Groupe.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="libelle">Valeur initiale de la propriété Libelle.</param>
        /// <param name="iD_JourSemaine">Valeur initiale de la propriété ID_JourSemaine.</param>
        /// <param name="nbPlaces">Valeur initiale de la propriété NbPlaces.</param>
        /// <param name="iD_Saison">Valeur initiale de la propriété ID_Saison.</param>
        /// <param name="heureDebut">Valeur initiale de la propriété HeureDebut.</param>
        /// <param name="heureFin">Valeur initiale de la propriété HeureFin.</param>
        public static Groupe CreateGroupe(global::System.Guid id, global::System.String libelle, global::System.Guid iD_JourSemaine, global::System.Int32 nbPlaces, global::System.Guid iD_Saison, global::System.DateTime heureDebut, global::System.DateTime heureFin)
        {
            Groupe groupe = new Groupe();
            groupe.ID = id;
            groupe.Libelle = libelle;
            groupe.ID_JourSemaine = iD_JourSemaine;
            groupe.NbPlaces = nbPlaces;
            groupe.ID_Saison = iD_Saison;
            groupe.HeureDebut = heureDebut;
            groupe.HeureFin = heureFin;
            return groupe;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Libelle
        {
            get
            {
                return _Libelle;
            }
            set
            {
                OnLibelleChanging(value);
                ReportPropertyChanging("Libelle");
                _Libelle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Libelle");
                OnLibelleChanged();
            }
        }
        private global::System.String _Libelle;
        partial void OnLibelleChanging(global::System.String value);
        partial void OnLibelleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID_JourSemaine
        {
            get
            {
                return _ID_JourSemaine;
            }
            set
            {
                OnID_JourSemaineChanging(value);
                ReportPropertyChanging("ID_JourSemaine");
                _ID_JourSemaine = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_JourSemaine");
                OnID_JourSemaineChanged();
            }
        }
        private global::System.Guid _ID_JourSemaine;
        partial void OnID_JourSemaineChanging(global::System.Guid value);
        partial void OnID_JourSemaineChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NbPlaces
        {
            get
            {
                return _NbPlaces;
            }
            set
            {
                OnNbPlacesChanging(value);
                ReportPropertyChanging("NbPlaces");
                _NbPlaces = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NbPlaces");
                OnNbPlacesChanged();
            }
        }
        private global::System.Int32 _NbPlaces;
        partial void OnNbPlacesChanging(global::System.Int32 value);
        partial void OnNbPlacesChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Commentaire
        {
            get
            {
                return _Commentaire;
            }
            set
            {
                OnCommentaireChanging(value);
                ReportPropertyChanging("Commentaire");
                _Commentaire = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Commentaire");
                OnCommentaireChanged();
            }
        }
        private global::System.String _Commentaire;
        partial void OnCommentaireChanging(global::System.String value);
        partial void OnCommentaireChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID_Saison
        {
            get
            {
                return _ID_Saison;
            }
            set
            {
                OnID_SaisonChanging(value);
                ReportPropertyChanging("ID_Saison");
                _ID_Saison = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Saison");
                OnID_SaisonChanged();
            }
        }
        private global::System.Guid _ID_Saison;
        partial void OnID_SaisonChanging(global::System.Guid value);
        partial void OnID_SaisonChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime HeureDebut
        {
            get
            {
                return _HeureDebut;
            }
            set
            {
                OnHeureDebutChanging(value);
                ReportPropertyChanging("HeureDebut");
                _HeureDebut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeureDebut");
                OnHeureDebutChanged();
            }
        }
        private global::System.DateTime _HeureDebut;
        partial void OnHeureDebutChanging(global::System.DateTime value);
        partial void OnHeureDebutChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime HeureFin
        {
            get
            {
                return _HeureFin;
            }
            set
            {
                OnHeureFinChanging(value);
                ReportPropertyChanging("HeureFin");
                _HeureFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeureFin");
                OnHeureFinChanged();
            }
        }
        private global::System.DateTime _HeureFin;
        partial void OnHeureFinChanging(global::System.DateTime value);
        partial void OnHeureFinChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gestadh45Model", Name="InfosClub")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InfosClub : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet InfosClub.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        public static InfosClub CreateInfosClub(global::System.Guid id, global::System.String nom)
        {
            InfosClub infosClub = new InfosClub();
            infosClub.ID = id;
            infosClub.Nom = nom;
            return infosClub;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.String _Numero;
        partial void OnNumeroChanging(global::System.String value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Siren
        {
            get
            {
                return _Siren;
            }
            set
            {
                OnSirenChanging(value);
                ReportPropertyChanging("Siren");
                _Siren = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Siren");
                OnSirenChanged();
            }
        }
        private global::System.String _Siren;
        partial void OnSirenChanging(global::System.String value);
        partial void OnSirenChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NIC
        {
            get
            {
                return _NIC;
            }
            set
            {
                OnNICChanging(value);
                ReportPropertyChanging("NIC");
                _NIC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NIC");
                OnNICChanged();
            }
        }
        private global::System.String _NIC;
        partial void OnNICChanging(global::System.String value);
        partial void OnNICChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adresse
        {
            get
            {
                return _Adresse;
            }
            set
            {
                OnAdresseChanging(value);
                ReportPropertyChanging("Adresse");
                _Adresse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adresse");
                OnAdresseChanged();
            }
        }
        private global::System.String _Adresse;
        partial void OnAdresseChanging(global::System.String value);
        partial void OnAdresseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ID_Ville
        {
            get
            {
                return _ID_Ville;
            }
            set
            {
                OnID_VilleChanging(value);
                ReportPropertyChanging("ID_Ville");
                _ID_Ville = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Ville");
                OnID_VilleChanged();
            }
        }
        private Nullable<global::System.Guid> _ID_Ville;
        partial void OnID_VilleChanging(Nullable<global::System.Guid> value);
        partial void OnID_VilleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private global::System.String _Telephone;
        partial void OnTelephoneChanging(global::System.String value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mail
        {
            get
            {
                return _Mail;
            }
            set
            {
                OnMailChanging(value);
                ReportPropertyChanging("Mail");
                _Mail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mail");
                OnMailChanged();
            }
        }
        private global::System.String _Mail;
        partial void OnMailChanging(global::System.String value);
        partial void OnMailChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SiteWeb
        {
            get
            {
                return _SiteWeb;
            }
            set
            {
                OnSiteWebChanging(value);
                ReportPropertyChanging("SiteWeb");
                _SiteWeb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SiteWeb");
                OnSiteWebChanged();
            }
        }
        private global::System.String _SiteWeb;
        partial void OnSiteWebChanging(global::System.String value);
        partial void OnSiteWebChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumAPS
        {
            get
            {
                return _NumAPS;
            }
            set
            {
                OnNumAPSChanging(value);
                ReportPropertyChanging("NumAPS");
                _NumAPS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumAPS");
                OnNumAPSChanged();
            }
        }
        private global::System.String _NumAPS;
        partial void OnNumAPSChanging(global::System.String value);
        partial void OnNumAPSChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gestadh45Model", Name="JourSemaine")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class JourSemaine : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet JourSemaine.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="numero">Valeur initiale de la propriété Numero.</param>
        /// <param name="libelle">Valeur initiale de la propriété Libelle.</param>
        public static JourSemaine CreateJourSemaine(global::System.Guid id, global::System.Int32 numero, global::System.String libelle)
        {
            JourSemaine jourSemaine = new JourSemaine();
            jourSemaine.ID = id;
            jourSemaine.Numero = numero;
            jourSemaine.Libelle = libelle;
            return jourSemaine;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.Int32 _Numero;
        partial void OnNumeroChanging(global::System.Int32 value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Libelle
        {
            get
            {
                return _Libelle;
            }
            set
            {
                OnLibelleChanging(value);
                ReportPropertyChanging("Libelle");
                _Libelle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Libelle");
                OnLibelleChanged();
            }
        }
        private global::System.String _Libelle;
        partial void OnLibelleChanging(global::System.String value);
        partial void OnLibelleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gestadh45Model", Name="Saison")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Saison : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Saison.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="estSaisonCourante">Valeur initiale de la propriété EstSaisonCourante.</param>
        /// <param name="anneeDebut">Valeur initiale de la propriété AnneeDebut.</param>
        public static Saison CreateSaison(global::System.Guid id, global::System.Boolean estSaisonCourante, global::System.Int32 anneeDebut)
        {
            Saison saison = new Saison();
            saison.ID = id;
            saison.EstSaisonCourante = estSaisonCourante;
            saison.AnneeDebut = anneeDebut;
            return saison;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EstSaisonCourante
        {
            get
            {
                return _EstSaisonCourante;
            }
            set
            {
                OnEstSaisonCouranteChanging(value);
                ReportPropertyChanging("EstSaisonCourante");
                _EstSaisonCourante = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EstSaisonCourante");
                OnEstSaisonCouranteChanged();
            }
        }
        private global::System.Boolean _EstSaisonCourante;
        partial void OnEstSaisonCouranteChanging(global::System.Boolean value);
        partial void OnEstSaisonCouranteChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AnneeDebut
        {
            get
            {
                return _AnneeDebut;
            }
            set
            {
                OnAnneeDebutChanging(value);
                ReportPropertyChanging("AnneeDebut");
                _AnneeDebut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnneeDebut");
                OnAnneeDebutChanged();
            }
        }
        private global::System.Int32 _AnneeDebut;
        partial void OnAnneeDebutChanging(global::System.Int32 value);
        partial void OnAnneeDebutChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AnneeFin
        {
            get
            {
                return _AnneeFin;
            }
            set
            {
                OnAnneeFinChanging(value);
                ReportPropertyChanging("AnneeFin");
                _AnneeFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnneeFin");
                OnAnneeFinChanged();
            }
        }
        private Nullable<global::System.Int32> _AnneeFin;
        partial void OnAnneeFinChanging(Nullable<global::System.Int32> value);
        partial void OnAnneeFinChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gestadh45Model", Name="Sexe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sexe : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Sexe.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="libelleCourt">Valeur initiale de la propriété LibelleCourt.</param>
        /// <param name="libelleLong">Valeur initiale de la propriété LibelleLong.</param>
        public static Sexe CreateSexe(global::System.Guid id, global::System.String libelleCourt, global::System.String libelleLong)
        {
            Sexe sexe = new Sexe();
            sexe.ID = id;
            sexe.LibelleCourt = libelleCourt;
            sexe.LibelleLong = libelleLong;
            return sexe;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LibelleCourt
        {
            get
            {
                return _LibelleCourt;
            }
            set
            {
                OnLibelleCourtChanging(value);
                ReportPropertyChanging("LibelleCourt");
                _LibelleCourt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LibelleCourt");
                OnLibelleCourtChanged();
            }
        }
        private global::System.String _LibelleCourt;
        partial void OnLibelleCourtChanging(global::System.String value);
        partial void OnLibelleCourtChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LibelleLong
        {
            get
            {
                return _LibelleLong;
            }
            set
            {
                OnLibelleLongChanging(value);
                ReportPropertyChanging("LibelleLong");
                _LibelleLong = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LibelleLong");
                OnLibelleLongChanged();
            }
        }
        private global::System.String _LibelleLong;
        partial void OnLibelleLongChanging(global::System.String value);
        partial void OnLibelleLongChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gestadh45Model", Name="StatutInscription")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StatutInscription : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet StatutInscription.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="libelle">Valeur initiale de la propriété Libelle.</param>
        /// <param name="codeCouleur">Valeur initiale de la propriété CodeCouleur.</param>
        /// <param name="ordre">Valeur initiale de la propriété Ordre.</param>
        public static StatutInscription CreateStatutInscription(global::System.Guid id, global::System.String libelle, global::System.String codeCouleur, global::System.Int32 ordre)
        {
            StatutInscription statutInscription = new StatutInscription();
            statutInscription.ID = id;
            statutInscription.Libelle = libelle;
            statutInscription.CodeCouleur = codeCouleur;
            statutInscription.Ordre = ordre;
            return statutInscription;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Libelle
        {
            get
            {
                return _Libelle;
            }
            set
            {
                OnLibelleChanging(value);
                ReportPropertyChanging("Libelle");
                _Libelle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Libelle");
                OnLibelleChanged();
            }
        }
        private global::System.String _Libelle;
        partial void OnLibelleChanging(global::System.String value);
        partial void OnLibelleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodeCouleur
        {
            get
            {
                return _CodeCouleur;
            }
            set
            {
                OnCodeCouleurChanging(value);
                ReportPropertyChanging("CodeCouleur");
                _CodeCouleur = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CodeCouleur");
                OnCodeCouleurChanged();
            }
        }
        private global::System.String _CodeCouleur;
        partial void OnCodeCouleurChanging(global::System.String value);
        partial void OnCodeCouleurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ordre
        {
            get
            {
                return _Ordre;
            }
            set
            {
                OnOrdreChanging(value);
                ReportPropertyChanging("Ordre");
                _Ordre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ordre");
                OnOrdreChanged();
            }
        }
        private global::System.Int32 _Ordre;
        partial void OnOrdreChanging(global::System.Int32 value);
        partial void OnOrdreChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gestadh45Model", Name="TrancheAge")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TrancheAge : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet TrancheAge.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="ageInf">Valeur initiale de la propriété AgeInf.</param>
        /// <param name="ageSup">Valeur initiale de la propriété AgeSup.</param>
        public static TrancheAge CreateTrancheAge(global::System.Guid id, global::System.Int32 ageInf, global::System.Int32 ageSup)
        {
            TrancheAge trancheAge = new TrancheAge();
            trancheAge.ID = id;
            trancheAge.AgeInf = ageInf;
            trancheAge.AgeSup = ageSup;
            return trancheAge;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AgeInf
        {
            get
            {
                return _AgeInf;
            }
            set
            {
                OnAgeInfChanging(value);
                ReportPropertyChanging("AgeInf");
                _AgeInf = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AgeInf");
                OnAgeInfChanged();
            }
        }
        private global::System.Int32 _AgeInf;
        partial void OnAgeInfChanging(global::System.Int32 value);
        partial void OnAgeInfChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AgeSup
        {
            get
            {
                return _AgeSup;
            }
            set
            {
                OnAgeSupChanging(value);
                ReportPropertyChanging("AgeSup");
                _AgeSup = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AgeSup");
                OnAgeSupChanged();
            }
        }
        private global::System.Int32 _AgeSup;
        partial void OnAgeSupChanging(global::System.Int32 value);
        partial void OnAgeSupChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gestadh45Model", Name="Ville")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ville : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Ville.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="libelle">Valeur initiale de la propriété Libelle.</param>
        /// <param name="codePostal">Valeur initiale de la propriété CodePostal.</param>
        public static Ville CreateVille(global::System.Guid id, global::System.String libelle, global::System.String codePostal)
        {
            Ville ville = new Ville();
            ville.ID = id;
            ville.Libelle = libelle;
            ville.CodePostal = codePostal;
            return ville;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Libelle
        {
            get
            {
                return _Libelle;
            }
            set
            {
                OnLibelleChanging(value);
                ReportPropertyChanging("Libelle");
                _Libelle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Libelle");
                OnLibelleChanged();
            }
        }
        private global::System.String _Libelle;
        partial void OnLibelleChanging(global::System.String value);
        partial void OnLibelleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodePostal
        {
            get
            {
                return _CodePostal;
            }
            set
            {
                OnCodePostalChanging(value);
                ReportPropertyChanging("CodePostal");
                _CodePostal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CodePostal");
                OnCodePostalChanged();
            }
        }
        private global::System.String _CodePostal;
        partial void OnCodePostalChanging(global::System.String value);
        partial void OnCodePostalChanged();

        #endregion
    
    }

    #endregion
    
}
