//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace gestadh45.poco
{
    public partial class InfosClub
    {
        #region Primitive Properties
    
        public virtual long ID
        {
            get;
            set;
        }
    
        public virtual string Nom
        {
            get;
            set;
        }
    
        public virtual string Numero
        {
            get;
            set;
        }
    
        public virtual string Siren
        {
            get;
            set;
        }
    
        public virtual string NIC
        {
            get;
            set;
        }
    
        public virtual string Adresse
        {
            get;
            set;
        }
    
        public virtual Nullable<long> ID_Ville
        {
            get { return _iD_Ville; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_iD_Ville != value)
                    {
                        if (Ville != null && Ville.ID != value)
                        {
                            Ville = null;
                        }
                        _iD_Ville = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<long> _iD_Ville;
    
        public virtual string Telephone
        {
            get;
            set;
        }
    
        public virtual string Mail
        {
            get;
            set;
        }
    
        public virtual string SiteWeb
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Ville Ville
        {
            get { return _ville; }
            set
            {
                if (!ReferenceEquals(_ville, value))
                {
                    var previousValue = _ville;
                    _ville = value;
                    FixupVille(previousValue);
                }
            }
        }
        private Ville _ville;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupVille(Ville previousValue)
        {
            if (previousValue != null && previousValue.InfosClub.Contains(this))
            {
                previousValue.InfosClub.Remove(this);
            }
    
            if (Ville != null)
            {
                if (!Ville.InfosClub.Contains(this))
                {
                    Ville.InfosClub.Add(this);
                }
                if (ID_Ville != Ville.ID)
                {
                    ID_Ville = Ville.ID;
                }
            }
            else if (!_settingFK)
            {
                ID_Ville = null;
            }
        }

        #endregion
    }
}
