//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace gestadh45.poco
{
    public partial class Saison
    {
        #region Primitive Properties
    
        public virtual long ID
        {
            get;
            set;
        }
    
        public virtual long EstSaisonCourante
        {
            get;
            set;
        }
    
        public virtual long AnneeDebut
        {
            get;
            set;
        }
    
        public virtual long AnneeFin
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Groupe> Groupe
        {
            get
            {
                if (_groupe == null)
                {
                    var newCollection = new FixupCollection<Groupe>();
                    newCollection.CollectionChanged += FixupGroupe;
                    _groupe = newCollection;
                }
                return _groupe;
            }
            set
            {
                if (!ReferenceEquals(_groupe, value))
                {
                    var previousValue = _groupe as FixupCollection<Groupe>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGroupe;
                    }
                    _groupe = value;
                    var newValue = value as FixupCollection<Groupe>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGroupe;
                    }
                }
            }
        }
        private ICollection<Groupe> _groupe;

        #endregion
        #region Association Fixup
    
        private void FixupGroupe(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Groupe item in e.NewItems)
                {
                    item.Saison = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Groupe item in e.OldItems)
                {
                    if (ReferenceEquals(item.Saison, this))
                    {
                        item.Saison = null;
                    }
                }
            }
        }

        #endregion
    }
}
