//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace gestadh45.poco
{
    public partial class StatutInscription
    {
        #region Primitive Properties
    
        public virtual long ID
        {
            get;
            set;
        }
    
        public virtual string Libelle
        {
            get;
            set;
        }
    
        public virtual string CodeCouleur
        {
            get;
            set;
        }
    
        public virtual long Ordre
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Inscription> Inscription
        {
            get
            {
                if (_inscription == null)
                {
                    var newCollection = new FixupCollection<Inscription>();
                    newCollection.CollectionChanged += FixupInscription;
                    _inscription = newCollection;
                }
                return _inscription;
            }
            set
            {
                if (!ReferenceEquals(_inscription, value))
                {
                    var previousValue = _inscription as FixupCollection<Inscription>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupInscription;
                    }
                    _inscription = value;
                    var newValue = value as FixupCollection<Inscription>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupInscription;
                    }
                }
            }
        }
        private ICollection<Inscription> _inscription;

        #endregion
        #region Association Fixup
    
        private void FixupInscription(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Inscription item in e.NewItems)
                {
                    item.StatutInscription = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Inscription item in e.OldItems)
                {
                    if (ReferenceEquals(item.StatutInscription, this))
                    {
                        item.StatutInscription = null;
                    }
                }
            }
        }

        #endregion
    }
}
