//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace gestadh45.poco
{
    public partial class Entities : ObjectContext
    {
        public const string ConnectionString = "name=Entities";
        public const string ContainerName = "Entities";
    
        #region Constructors
    
        public Entities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public Entities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public Entities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Adherent> Adherent
        {
            get { return _adherent  ?? (_adherent = CreateObjectSet<Adherent>("Adherent")); }
        }
        private ObjectSet<Adherent> _adherent;
    
        public ObjectSet<Groupe> Groupe
        {
            get { return _groupe  ?? (_groupe = CreateObjectSet<Groupe>("Groupe")); }
        }
        private ObjectSet<Groupe> _groupe;
    
        public ObjectSet<InfosClub> InfosClub
        {
            get { return _infosClub  ?? (_infosClub = CreateObjectSet<InfosClub>("InfosClub")); }
        }
        private ObjectSet<InfosClub> _infosClub;
    
        public ObjectSet<Inscription> Inscription
        {
            get { return _inscription  ?? (_inscription = CreateObjectSet<Inscription>("Inscription")); }
        }
        private ObjectSet<Inscription> _inscription;
    
        public ObjectSet<JourSemaine> JourSemaine
        {
            get { return _jourSemaine  ?? (_jourSemaine = CreateObjectSet<JourSemaine>("JourSemaine")); }
        }
        private ObjectSet<JourSemaine> _jourSemaine;
    
        public ObjectSet<Saison> Saison
        {
            get { return _saison  ?? (_saison = CreateObjectSet<Saison>("Saison")); }
        }
        private ObjectSet<Saison> _saison;
    
        public ObjectSet<Sexe> Sexe
        {
            get { return _sexe  ?? (_sexe = CreateObjectSet<Sexe>("Sexe")); }
        }
        private ObjectSet<Sexe> _sexe;
    
        public ObjectSet<StatutInscription> StatutInscription
        {
            get { return _statutInscription  ?? (_statutInscription = CreateObjectSet<StatutInscription>("StatutInscription")); }
        }
        private ObjectSet<StatutInscription> _statutInscription;
    
        public ObjectSet<Ville> Ville
        {
            get { return _ville  ?? (_ville = CreateObjectSet<Ville>("Ville")); }
        }
        private ObjectSet<Ville> _ville;

        #endregion
    }
}
