//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestadh45.service.Documents {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResDocuments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResDocuments() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gestadh45.service.Documents.ResDocuments", typeof(ResDocuments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à €.
        /// </summary>
        internal static string Devise {
            get {
                return ResourceManager.GetString("Devise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        internal static string LibelleAdresse {
            get {
                return ResourceManager.GetString("LibelleAdresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à au club.
        /// </summary>
        internal static string LibelleAuClub {
            get {
                return ResourceManager.GetString("LibelleAuClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autorisation parentale pour les mineurs.
        /// </summary>
        internal static string LibelleAutorisationParentale {
            get {
                return ResourceManager.GetString("LibelleAutorisationParentale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code postal.
        /// </summary>
        internal static string LibelleCodePostal {
            get {
                return ResourceManager.GetString("LibelleCodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cotisation.
        /// </summary>
        internal static string LibelleCotisation {
            get {
                return ResourceManager.GetString("LibelleCotisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de naissance.
        /// </summary>
        internal static string LibelleDateNaissance {
            get {
                return ResourceManager.GetString("LibelleDateNaissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fait à.
        /// </summary>
        internal static string LibelleFaitA {
            get {
                return ResourceManager.GetString("LibelleFaitA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fait à .............................. le ...............................
        /// </summary>
        internal static string LibelleFaitALe {
            get {
                return ResourceManager.GetString("LibelleFaitALe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe.
        /// </summary>
        internal static string LibelleGroupe {
            get {
                return ResourceManager.GetString("LibelleGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à le.
        /// </summary>
        internal static string LibelleLe {
            get {
                return ResourceManager.GetString("LibelleLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mail 1.
        /// </summary>
        internal static string LibelleMail1 {
            get {
                return ResourceManager.GetString("LibelleMail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mail 2.
        /// </summary>
        internal static string LibelleMail2 {
            get {
                return ResourceManager.GetString("LibelleMail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mail 3.
        /// </summary>
        internal static string LibelleMail3 {
            get {
                return ResourceManager.GetString("LibelleMail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        internal static string LibelleNom {
            get {
                return ResourceManager.GetString("LibelleNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        internal static string LibellePrenom {
            get {
                return ResourceManager.GetString("LibellePrenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reçu pour l&apos;adhésion.
        /// </summary>
        internal static string LibelleRecuPourLAdhesion {
            get {
                return ResourceManager.GetString("LibelleRecuPourLAdhesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAISON.
        /// </summary>
        internal static string LibelleSaison {
            get {
                return ResourceManager.GetString("LibelleSaison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signature de l&apos;adhérent ou de son représentant légal.
        /// </summary>
        internal static string LibelleSignatureAdherent {
            get {
                return ResourceManager.GetString("LibelleSignatureAdherent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signature.
        /// </summary>
        internal static string LibelleSignatureParent {
            get {
                return ResourceManager.GetString("LibelleSignatureParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone 1.
        /// </summary>
        internal static string LibelleTelephone1 {
            get {
                return ResourceManager.GetString("LibelleTelephone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone 2.
        /// </summary>
        internal static string LibelleTelephone2 {
            get {
                return ResourceManager.GetString("LibelleTelephone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone 3.
        /// </summary>
        internal static string LibelleTelephone3 {
            get {
                return ResourceManager.GetString("LibelleTelephone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville.
        /// </summary>
        internal static string LibelleVille {
            get {
                return ResourceManager.GetString("LibelleVille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E-mail.
        /// </summary>
        internal static string PrefixeMail {
            get {
                return ResourceManager.GetString("PrefixeMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° asso..
        /// </summary>
        internal static string PrefixeNumeroClub {
            get {
                return ResourceManager.GetString("PrefixeNumeroClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SIREN.
        /// </summary>
        internal static string PrefixeSiren {
            get {
                return ResourceManager.GetString("PrefixeSiren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web.
        /// </summary>
        internal static string PrefixeSiteWeb {
            get {
                return ResourceManager.GetString("PrefixeSiteWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tel..
        /// </summary>
        internal static string PrefixeTelephone {
            get {
                return ResourceManager.GetString("PrefixeTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je, soussigné .................................................., agissant en qualité de parent ou de tuteur légal de l&apos;enfant désigné ci-dessus, autorise le club à faire transporter mon enfant au centre hospitalier le plus proche si son état le nécessite ou a prendre toutes les mesures nécessaires en cas d&apos;accident survenant lors de la pratique de l&apos;escalade dans le cadre du club..
        /// </summary>
        internal static string TexteAutorisationParentale {
            get {
                return ResourceManager.GetString("TexteAutorisationParentale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fiche d&apos;inscription.
        /// </summary>
        internal static string TitreFicheInscription {
            get {
                return ResourceManager.GetString("TitreFicheInscription", resourceCulture);
            }
        }
    }
}
